version: "3.8"

services:
  database:
    image: postgres:9.6
    expose:
      - "5432"
    environment:
      POSTGRES_PASSWORD: "spider_pass"
      PGPASSWORD: "spider_pass"
  connection-pooler:
    image: edoburu/pgbouncer:1.12.0
    expose:
      - "5432"
    environment:
      DB_USER: "postgres"
      DB_PASSWORD: "spider_pass"
      PGPASSWORD: "spider_pass"
      DB_HOST: "database"
      POOL_MODE: "transaction"
  client:
    image: postgres:9.6
    environment:
      PGUSER: "postgres"
      PGPASSWORD: "spider_pass"
      PGHOST: "database"
    command: tail -f /dev/null
