version: "3.8"

services:
  database:
    image: postgres:9.6
    expose:
      - "5432"
    environment:
      POSTGRES_PASSWORD: "safe"
  connection-pooler:
    image: edoburu/pgbouncer:1.12.0
    expose:
      - "5432"
    environment:
      DB_USER: "postgres"
      DB_PASSWORD: "safe"
      DB_HOST: "database"
      DB_NAME: "postgres"
